
 <template>
  <v-app id="content">
    <v-toolbar app id="toolbar">
      <v-toolbar-title class="headline text-uppercase">
        <span>Robot</span>
        <span class="font-weight-light">Car</span>
      </v-toolbar-title>

      <v-spacer></v-spacer>
      <v-btn color="orange" dark @click.stop="dialog = true">Conncet</v-btn>
      <v-btn target="_blank" @click="Switch=!Switch">
        <span v-if="Switch!==true" class="mr-2">Main</span>
        <span v-else class="mr-2">Ide</span>
      </v-btn>
    </v-toolbar>

    <v-content>
      <v-row align="center" justify="center">
        <v-dialog v-model="dialog" max-width="290" height="290">
          <v-card>
            <v-card-title class="headline">Connect to Server</v-card-title>

            <v-card-text style="height: 300px;">
              <v-text-field v-model="name" label="Name" filled></v-text-field>

              <v-text-field v-model="password" label="MQTT Password" filled></v-text-field>

              <v-text-field v-model="port" label="Port" filled></v-text-field>
              <v-text-field v-model="adress" label="Adress" filled></v-text-field>
            </v-card-text>

            <v-card-actions>
              <v-spacer></v-spacer>

              <v-btn color="orange" dark @click="save()">Spara</v-btn>
            </v-card-actions>
          </v-card>
        </v-dialog>

        <div>
          <Logger />

          <Buttons v-if="Switch" />
          <ButtonsMain v-else />
        </div>
      </v-row> 
      </v-content>
     
  <!-- <v-card class= "my-1"> -->
  <v-bottom-navigation
    v-model="bottomNav"
  >
    <v-btn value="recent">
      <span>Recent</span>
      <v-icon>mdi-history</v-icon>
    </v-btn>

    <v-btn value="favorites">
      <span>Favorites</span>
      <v-icon>mdi-heart</v-icon>
    </v-btn>

    <v-btn value="nearby">
      <span>Nearby</span>
      <v-icon>mdi-map-marker</v-icon>
    </v-btn>
  </v-bottom-navigation>
</v-app>
 
</template>
<script>
//<template>
//  <v-app>
//   <core-Toolbar/>
//     <!-- <v-btn @click="connect">Connect</v-btn>
//     <v-btn @click="send">Send</v-btn> -->
//   <router-view/> 
//      <v-card class= "my-1">
//            <v-bottom-navigation
//            grow
//            fixed
//     :value="activeBtn"
//     color="deep-purple accent-4"
//   >
//     <v-btn to="/">
//       <span>Home</span>
//       <v-icon>mdi-home</v-icon>
//     </v-btn>

//         <v-btn to="/Color">
//           <span>Color</span>
//           <v-icon>mdi-palette</v-icon>
//         </v-btn>

//         <v-btn to="/About">
//           <span>Info</span>
//           <v-icon>mdi-information-variant</v-icon>
//         </v-btn>

//         <v-btn to="/Settings">
//       <span>Settings</span>
//       <v-icon>mdi-cog-outline</v-icon>
//     </v-btn>
//       </v-bottom-navigation>
//     </v-card>
//   </v-app>
// </template>

import ButtonsMain from "./components/ButtonsMain";
import Buttons from "./components/Buttons";
import Logger from "./components/Logger";

  
export default {
  name: "App",
  components: {
    Buttons,
    ButtonsMain,
    Logger
  },
  data() {
    return {
      Switch: false,
      dialog: false,
      name: "",
      password: "",
      port: "",
      adress: "",
      bottomNav: 'recent'
    };
  },
  created() {
    let User = this.$store.getters.GetUser;
    this.name = User.name;
    this.password = User.password;
    this.port = User.port;
    this.adress = User.adress;
  },

  methods: {
    save() {
      let User = {
        name: this.name,
        password: this.password,
        port: this.port,
        adress: this.adress
      };

      this.$store.dispatch("Save", User);

      this.dialog = false;
    }
  },
  computed: {}
};
</script>
<style scoped>
.img {
  width: 40%;
  height: 40%;
  margin: auto;
  padding: 10px;
}
#logger {
  /* position: fixed;
  bottom: 0;
  right: 0; */
  width: 300px;
  height: 300px;
  border: black dotted 2px;

  word-wrap: break-word;
}
#toolbar {
  background-image: url("data:image/svg+xml,%3C!-- SVG Pattern generated by 𝕭𝖊𝖆𝖚𝖙𝖎𝖋𝖚𝖑 𝕯𝖎𝖓𝖌𝖇𝖆𝖙𝖘 --%3E%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='100%25' height='100%25'%3E%3Cdefs%3E%3Cpattern id='pattern' width='28' height='28' viewBox='0 0 40 40' patternUnits='userSpaceOnUse' patternTransform='rotate(112)'%3E%3Crect id='pattern-background' x='0' y='0' width='400%25' height='400%25' fill='%23FF8A80'/%3E%3Ccircle cx='5' cy='15' r='3' fill='%23e03131' stroke='%23e03131' stroke-width='0'/%3E%3Ccircle cx='25' cy='15' r='3' fill='%23e03131' stroke='%23e03131' stroke-width='0'/%3E%3Ccircle cx='15' cy='25' r='3' fill='%23e03131' stroke='%23e03131' stroke-width='0'/%3E%3Ccircle cx='35' cy='25' r='3' fill='%23e03131' stroke='%23e03131' stroke-width='0'/%3E%3C!----%3E%3C!----%3E%3Ccircle cx='15' cy='15' r='2.25' fill='%23343a40' stroke='%23343a40' stroke-width='0'/%3E%3Ccircle cx='35' cy='15' r='2.25' fill='%23343a40' stroke='%23343a40' stroke-width='0'/%3E%3Ccircle cx='5' cy='25' r='2.25' fill='%23343a40' stroke='%23343a40' stroke-width='0'/%3E%3Ccircle cx='25' cy='25' r='2.25' fill='%23343a40' stroke='%23343a40' stroke-width='0'/%3E%3C!----%3E%3C!----%3E%3C/pattern%3E%3C/defs%3E%3Crect fill='url(%23pattern)' height='100%25' width='100%25' y='0' x='0'/%3E%3C/svg%3E");
}
#content {
  background-image: url("data:image/svg+xml,%3C!-- SVG Pattern generated by 𝕭𝖊𝖆𝖚𝖙𝖎𝖋𝖚𝖑 𝕯𝖎𝖓𝖌𝖇𝖆𝖙𝖘 --%3E%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='100%25' height='100%25'%3E%3Cdefs%3E%3Cpattern id='pattern' width='49' height='49' viewBox='0 0 40 40' patternUnits='userSpaceOnUse' patternTransform='rotate(52)'%3E%3Crect id='pattern-background' x='0' y='0' width='400%25' height='400%25' fill='%23495057'/%3E%3C!----%3E%3C!----%3E%3Cpath d='M0,20 h10 v-6 h-10 z' fill='%23adb5bd' shape-rendering='auto' stroke-width='0' stroke='%23adb5bd' stroke-linejoin='round'/%3E%3Cpath d='M20,20 h10 v-6 h-10 z' fill='%23adb5bd' shape-rendering='auto' stroke-width='0' stroke='%23adb5bd' stroke-linejoin='round'/%3E%3Cpath d='M10,20 h10 v6 h-10 z' fill='%23adb5bd' shape-rendering='auto' stroke-width='0' stroke='%23adb5bd' stroke-linejoin='round'/%3E%3Cpath d='M30,20 h10 v6 h-10 z' fill='%23adb5bd' shape-rendering='auto' stroke-width='0' stroke='%23adb5bd' stroke-linejoin='round'/%3E%3C!----%3E%3C!----%3E%3Cpath d='M10,20 h10 v-4 h-10 z' fill='%231a202c' shape-rendering='auto' stroke-width='0' stroke='%231a202c' stroke-linejoin='round'/%3E%3Cpath d='M30,20 h10 v-4 h-10 z' fill='%231a202c' shape-rendering='auto' stroke-width='0' stroke='%231a202c' stroke-linejoin='round'/%3E%3Cpath d='M0,20 h10 v4 h-10 z' fill='%231a202c' shape-rendering='auto' stroke-width='0' stroke='%231a202c' stroke-linejoin='round'/%3E%3Cpath d='M20,20 h10 v4 h-10 z' fill='%231a202c' shape-rendering='auto' stroke-width='0' stroke='%231a202c' stroke-linejoin='round'/%3E%3C/pattern%3E%3C/defs%3E%3Crect fill='url(%23pattern)' height='100%25' width='100%25' y='0' x='0'/%3E%3C/svg%3E");
}

.my1{
  padding-bottom: 120px;
}



</style>


